# Generated by Django 5.2.1 on 2025-05-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numeros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(blank=True, max_length=50)),
                ('nome_completo', models.CharField(blank=True, max_length=50)),
                ('numero', models.CharField(blank=True, max_length=16)),
                ('pacote_dados_mb', models.PositiveIntegerField(blank=True, default=0, help_text='Tamanho do pacote de dados em MB')),
                ('setor', models.CharField(blank=True, max_length=50)),
                ('obra', models.CharField(blank=True, max_length=50)),
                ('imprimir', models.BooleanField(default=False, help_text='Marque para imprimir o número')),
            ],
        ),
    ]
