# Generated by Django 5.2.1 on 2025-05-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_lista_telefonica', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Numeros',
            new_name='Linhas',
        ),
    ]
