# Generated by Django 5.2.1 on 2025-05-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_lista_telefonica', '0002_rename_numeros_linhas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Linhas',
            new_name='Linha',
        ),
    ]
