# Generated by Django 5.2.1 on 2025-05-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_lista_ramal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramal',
            name='ramal',
            field=models.CharField(default='', max_length=4),
        ),
    ]
