# Generated by Django 5.2.1 on 2025-05-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_lista_ramal', '0002_ramal_ramal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramal',
            name='anydesk',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='ramal',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='ramal',
            name='nome',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ramal',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ramal',
            name='ramal',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='ramal',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
