# Generated by Django 5.2.1 on 2025-05-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_lista_ramal', '0003_alter_ramal_anydesk_alter_ramal_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramal',
            name='setor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
