# Generated by Django 5.2.1 on 2025-05-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_lista_ramal', '0004_ramal_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramal',
            name='nome_usuario',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
