# Generated by Django 5.2.1 on 2025-05-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_lista_ramal', '0006_alter_ramal_nome_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramal',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
