# Generated by Django 5.2.1 on 2025-05-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_lista_ramal', '0007_alter_ramal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramal',
            name='obra',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
