# Generated by Django 5.0.14 on 2025-06-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_lista_ramal', '0008_ramal_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramal',
            name='ramal',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
