# Generated by Django 5.0.14 on 2025-06-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_lista_ramal', '0009_alter_ramal_ramal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramal',
            name='numero_celular',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
