# Generated by Django 5.0.14 on 2025-06-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_lista_ramal', '0010_ramal_numero_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramal',
            name='ramal',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
